### ISSUE TITLE
Add incompatibility warning for prettier

### ISSUE THREAD

**Issue by chintai-paul** [osher/pino-prettier#1]
This package overwrites the [prettier](https://www.npmjs.com/package/prettier) utility.
Please add a incompatibility warning to the readme file, as the `prettier` package is very popular and the issue is hard to debug.

**Comment by osher** [comment]
OMG. must have missed that at the time... 🤔 
I should chose another name

**Comment by osher** [comment]
Just so you know I did not forget, I'm working on `v2.0.0` with that change, however, there is one more issue for compatibility with `nestjs` that must make it for that version.

it currently works only as a CLI and I was informed of a problem with requiring/importing the module for a `nestjs` adapter - I hope to get the quiet to solve it too :)

**Comment by osher** [comment]
OMG. I was blown away by other projects... sorry.
I published 2.0.0 w/o the nest fix :(
